export const GAME_PHASES = {
  TITLE: 'title',
  SETUP: 'setup',
  PLAYING: 'playing',
  BUILD_PHASE: 'build_phase',
  ENDED: 'ended',
}

export const ENVELOPE_CATEGORIES = {
  FOOD: 'FOOD_AND_DRINK',
  INCOME: 'INCOME',
  BILLS: 'RENT_AND_UTILITIES',
  SHOPPING: 'GENERAL_MERCHANDISE',
  ENTERTAINMENT: 'ENTERTAINMENT',
  TRANSPORTATION: 'TRANSPORTATION',
  TRANSFER: 'TRANSFER_OUT',
  BANK_FEE: 'BANK_FEES',
}

export const CATEGORY_COLORS = {
  FOOD_AND_DRINK: 0xe74c3c,
  INCOME: 0x2ecc71,
  RENT_AND_UTILITIES: 0x3498db,
  GENERAL_MERCHANDISE: 0xf1c40f,
  ENTERTAINMENT: 0x9b59b6,
  TRANSPORTATION: 0x95a5a6,
  TRANSFER_OUT: 0xecf0f1,
  TRANSFER_IN: 0xecf0f1,
  BANK_FEES: 0x1a1a1a,
  LOAN_PAYMENTS: 0x3498db,
  GENERAL_SERVICES: 0xf39c12,
  PERSONAL_CARE: 0xe91e63,
  MEDICAL: 0x00bcd4,
  GOVERNMENT_AND_NON_PROFIT: 0x607d8b,
  OTHER: 0x7f8c8d,
}

export const SORT_SLOTS = ['ACH_DEBIT', 'ACH_CREDIT', 'WIRE', 'RECURRING', 'RETURN']

export const ACH_RETURN_CODES = {
  R01: { code: 'R01', reason: 'Insufficient Funds', description: 'Available balance not sufficient to cover the dollar value of the debit.' },
  R02: { code: 'R02', reason: 'Account Closed', description: 'Previously active account has been closed.' },
  R03: { code: 'R03', reason: 'No Account / Unable to Locate', description: 'Account number does not correspond to an individual.' },
  R04: { code: 'R04', reason: 'Invalid Account Number', description: 'Account number structure is not valid.' },
  R05: { code: 'R05', reason: 'Unauthorized Debit', description: 'Consumer advises not authorized; notice not provided; signatures not genuine.' },
  R07: { code: 'R07', reason: 'Authorization Revoked', description: 'Consumer has revoked authorization.' },
  R08: { code: 'R08', reason: 'Payment Stopped', description: 'Receiver has placed a stop payment.' },
  R10: { code: 'R10', reason: 'Customer Advises Unauthorized', description: 'Consumer advises that the debit was not authorized.' },
  R29: { code: 'R29', reason: 'Corporate Customer Not Authorized', description: 'Corporate receiver advises not authorized.' },
}

export const EQUIPMENT_TYPES = {
  INTAKE_CONVEYOR: 'intake_conveyor',
  SORTING_DESK: 'sorting_desk',
  PNEUMATIC_TUBE: 'pneumatic_tube',
  BATCH_BIN: 'batch_bin',
  SETTLEMENT_VAULT: 'settlement_vault',
  AUTO_SORTER: 'auto_sorter',
  CONVEYOR_EXTENSION: 'conveyor_extension',
  RETURN_DESK: 'return_desk',
  STAMP_VALIDATOR: 'stamp_validator',
  AUTO_SEAL_BIN: 'auto_seal_bin',
  FRAUD_SCANNER: 'fraud_scanner',
  SPEED_BELT: 'speed_belt',
  DUPLICATE_DETECTOR: 'duplicate_detector',
  MEGA_BATCH_BIN: 'mega_batch_bin',
  LOAD_BALANCER: 'load_balancer',
  EXPRESS_INTAKE: 'express_intake',
  AI_SORTER: 'ai_sorter',
  QUALITY_CONTROL: 'quality_control',
  SAMEDAY_VAULT: 'sameday_vault',
  WIRE_TERMINAL: 'wire_terminal',
  PREMIUM_LANE: 'premium_lane',
  BACKUP_GENERATOR: 'backup_generator',
  HVAC_UNIT: 'hvac_unit',
  SURGE_BUFFER: 'surge_buffer',
  SURVEILLANCE_CAM: 'surveillance_cam',
  TELEPORT_PAD: 'teleport_pad',
  STAFF_DESK: 'staff_desk',
  POTTED_PLANT: 'potted_plant',
  WINDOW_BEACH: 'window_beach',
  WINDOW_FOREST: 'window_forest',
  RUBBER_DUCK: 'rubber_duck',
  COFFEE_MACHINE: 'coffee_machine',
}

export const EQUIPMENT_CATALOG = {
  [EQUIPMENT_TYPES.INTAKE_CONVEYOR]: {
    name: 'Intake Conveyor Belt',
    cost: 500,
    description: 'Receives envelopes from the loading dock. The entry point for all transactions.',
    tier: 1,
    gridSize: [3, 1],
  },
  [EQUIPMENT_TYPES.SORTING_DESK]: {
    name: 'Sorting Terminal',
    cost: 300,
    description: 'Envelopes queue here. Screen shows merchant, amount, and which bin to sort into. Color-coded reference strip.',
    tier: 1,
    gridSize: [2, 2],
  },
  [EQUIPMENT_TYPES.PNEUMATIC_TUBE]: {
    name: 'Basic Pneumatic Tube',
    cost: 150,
    description: 'Connects any two stations. Envelopes travel through visibly.',
    tier: 1,
    gridSize: [0, 0],
  },
  [EQUIPMENT_TYPES.BATCH_BIN]: {
    name: 'Batch Bin (Small)',
    cost: 400,
    description: 'Collects validated envelopes into settlement batches. Holds 25. Pull lever to seal.',
    tier: 1,
    gridSize: [2, 2],
    capacity: 25,
  },
  [EQUIPMENT_TYPES.SETTLEMENT_VAULT]: {
    name: 'Settlement Vault',
    cost: 1000,
    description: 'Receives sealed batches and settles them on a timed cycle.',
    tier: 1,
    gridSize: [3, 3],
  },
  [EQUIPMENT_TYPES.AUTO_SORTER]: {
    name: 'Automatic Sorting Machine',
    cost: 2500,
    description: 'Reads envelopes and routes them to the correct bin automatically. 85% accuracy — misroutes go to exception tray. Processes 1 envelope every 2 seconds.',
    tier: 2,
    gridSize: [3, 2],
  },
  [EQUIPMENT_TYPES.CONVEYOR_EXTENSION]: {
    name: 'Conveyor Extension Belt',
    cost: 350,
    description: 'Belt segment that carries envelopes between two points automatically. No more walking.',
    tier: 1,
    gridSize: [4, 1],
  },
  [EQUIPMENT_TYPES.RETURN_DESK]: {
    name: 'Return Processing Desk',
    cost: 800,
    description: 'Handles flagged return envelopes. Assign ACH return codes (R01, R02, R03...) to resolve. Required for return transactions.',
    tier: 1,
    gridSize: [2, 2],
  },
  [EQUIPMENT_TYPES.STAMP_VALIDATOR]: {
    name: 'Stamp Validation Machine',
    cost: 1500,
    description: 'Inline scanner that auto-approves clean envelopes and diverts suspicious ones to the return desk. Catches 90% of returns.',
    tier: 2,
    gridSize: [2, 1],
  },
  [EQUIPMENT_TYPES.AUTO_SEAL_BIN]: {
    name: 'Auto-Seal Batch Bin',
    cost: 1200,
    description: 'Large batch bin (50 capacity) that automatically seals and ships when full. No lever pulling needed.',
    tier: 2,
    gridSize: [2, 2],
    capacity: 50,
  },
  [EQUIPMENT_TYPES.FRAUD_SCANNER]: {
    name: 'Fraud Detection Scanner',
    cost: 1800,
    description: 'Archway scanner that flags transactions over $2,000 as suspicious. Flagged envelopes become returns. Catches big-ticket fraud.',
    tier: 2,
    gridSize: [2, 1],
  },
  [EQUIPMENT_TYPES.SPEED_BELT]: {
    name: 'High-Speed Conveyor',
    cost: 600,
    description: 'Moves envelopes at 3x normal speed. Place between stations for rapid transport.',
    tier: 1,
    gridSize: [4, 1],
  },
  [EQUIPMENT_TYPES.DUPLICATE_DETECTOR]: {
    name: 'Duplicate Transaction Detector',
    cost: 1200,
    description: 'Catches duplicate charges (same merchant + amount in a row). Diverts them for return processing. Saves penalties.',
    tier: 2,
    gridSize: [2, 1],
  },
  [EQUIPMENT_TYPES.MEGA_BATCH_BIN]: {
    name: 'Mega Batch Processor',
    cost: 3000,
    description: 'Industrial hopper holding 200 envelopes. Auto-seals and ships. The endgame batch solution.',
    tier: 3,
    gridSize: [3, 3],
    capacity: 200,
  },
  [EQUIPMENT_TYPES.LOAD_BALANCER]: {
    name: 'Load Balancer Junction',
    cost: 2000,
    description: 'Splits envelope flow evenly across all placed auto-sorters. Unlocks parallel processing.',
    tier: 2,
    gridSize: [2, 2],
  },
  [EQUIPMENT_TYPES.EXPRESS_INTAKE]: {
    name: 'Express Double-Wide Intake',
    cost: 1500,
    description: 'Wide intake conveyor that receives 3 envelopes at once. Critical for late-game flood.',
    tier: 2,
    gridSize: [4, 2],
  },
  [EQUIPMENT_TYPES.AI_SORTER]: {
    name: 'AI Pre-Sorter',
    cost: 4000,
    description: '95% accuracy sorting (vs 85% auto-sorter) but slower at 3s/envelope. Precision over speed.',
    tier: 3,
    gridSize: [3, 2],
  },
  [EQUIPMENT_TYPES.QUALITY_CONTROL]: {
    name: 'Quality Control Station',
    cost: 1800,
    description: 'Double-checks auto-sorter output. Catches misroutes before they get scored. Adds 1s delay.',
    tier: 2,
    gridSize: [2, 2],
  },
  [EQUIPMENT_TYPES.SAMEDAY_VAULT]: {
    name: 'Same-Day Settlement Vault',
    cost: 3500,
    description: 'Settles every 10s instead of 30s. Batch fees pay 2x premium. Real same-day ACH pricing.',
    tier: 3,
    gridSize: [3, 3],
  },
  [EQUIPMENT_TYPES.WIRE_TERMINAL]: {
    name: 'Wire Transfer Terminal',
    cost: 2500,
    description: 'Dedicated wire processing. Wire envelopes earn 10x basis points ($50+ on large wires).',
    tier: 2,
    gridSize: [2, 2],
  },
  [EQUIPMENT_TYPES.PREMIUM_LANE]: {
    name: 'Premium Processing Lane',
    cost: 2000,
    description: 'Envelopes over $1,000 routed here earn 2x basis points. Commercial ACH pricing tier.',
    tier: 2,
    gridSize: [3, 1],
  },
  [EQUIPMENT_TYPES.BACKUP_GENERATOR]: {
    name: 'Backup Generator',
    cost: 1500,
    description: 'Prevents random 10s power outages that freeze ALL automated equipment. Essential for late game.',
    tier: 2,
    gridSize: [2, 2],
  },
  [EQUIPMENT_TYPES.HVAC_UNIT]: {
    name: 'HVAC Climate Control',
    cost: 1000,
    description: 'Without HVAC: auto-sorter drops to 70% accuracy, AI sorter to 80%. With HVAC: full 85%/95%.',
    tier: 1,
    gridSize: [2, 1],
  },
  [EQUIPMENT_TYPES.SURGE_BUFFER]: {
    name: 'Surge Buffer Tank',
    cost: 1800,
    description: 'Absorbs envelope bursts and releases at steady rate. Smooths holiday rushes and payday floods.',
    tier: 2,
    gridSize: [2, 2],
  },
  [EQUIPMENT_TYPES.SURVEILLANCE_CAM]: {
    name: 'Surveillance Camera',
    cost: 500,
    description: 'Increases interaction range to 10m (from 6m). See and click things from further away.',
    tier: 1,
    gridSize: [1, 1],
  },
  [EQUIPMENT_TYPES.TELEPORT_PAD]: {
    name: 'Teleport Pad',
    cost: 800,
    description: 'Place two pads. Press T near one to teleport to the other. Eliminates walking time.',
    tier: 1,
    gridSize: [1, 1],
  },
  [EQUIPMENT_TYPES.STAFF_DESK]: {
    name: 'Staff NPC Desk',
    cost: 2000,
    description: 'Hires an NPC that manually sorts at 60% accuracy. Slow but handles overflow. $50/quarter salary.',
    tier: 2,
    gridSize: [2, 2],
  },
  [EQUIPMENT_TYPES.POTTED_PLANT]: {
    name: 'Potted Plant',
    cost: 50,
    description: 'A nice fern. Improves morale. Does absolutely nothing else. But look at it.',
    tier: 1,
    gridSize: [1, 1],
  },
  [EQUIPMENT_TYPES.WINDOW_BEACH]: {
    name: 'Window (Beach View)',
    cost: 200,
    description: 'A fake window showing a tropical beach. You deserve this. +0 productivity, +100 vibes.',
    tier: 1,
    gridSize: [1, 1],
  },
  [EQUIPMENT_TYPES.WINDOW_FOREST]: {
    name: 'Window (Forest View)',
    cost: 200,
    description: 'A fake window showing a misty forest. Very zen. Your envelopes feel calmer already.',
    tier: 1,
    gridSize: [1, 1],
  },
  [EQUIPMENT_TYPES.RUBBER_DUCK]: {
    name: 'Rubber Duck',
    cost: 25,
    description: 'Every good debugging session needs a rubber duck. Place it. Talk to it. It understands.',
    tier: 1,
    gridSize: [1, 1],
  },
  [EQUIPMENT_TYPES.COFFEE_MACHINE]: {
    name: 'Coffee Machine',
    cost: 150,
    description: 'Increases player walk speed by 20% when placed. Caffeine is a feature, not a bug.',
    tier: 1,
    gridSize: [1, 1],
  },
}

export const BUILDING = {
  WIDTH: 40,
  DEPTH: 30,
  HEIGHT: 8,
  WALL_THICKNESS: 0.5,
  GRID_CELL: 1,
}

export const TIME_COMPRESSION = {
  TOTAL_GAME_DURATION_SEC: 45 * 60,
  QUARTERS: 8,
  BUILD_PHASE_DURATION_SEC: 60,
}
